const productsData = [
  {
    id: 1,
    name: 'Monstera Deliciosa',
    category: 'Indoor',
    price: 29.99,
    description: 'Large iconic split leaves that bring a tropical vibe to any room. Easy to care for and fast-growing.',
    image: '🌿',
  },
  {
    id: 2,
    name: 'Snake Plant',
    category: 'Indoor',
    price: 19.99,
    description: 'Nearly indestructible air-purifying plant. Thrives on neglect and low light conditions.',
    image: '🌱',
  },
  {
    id: 3,
    name: 'Fiddle Leaf Fig',
    category: 'Indoor',
    price: 39.99,
    description: 'Trendy tall plant with large violin-shaped leaves. A statement piece for any living space.',
    image: '🌳',
  },
  {
    id: 4,
    name: 'Peace Lily',
    category: 'Indoor',
    price: 24.99,
    description: 'Elegant white blooms and glossy green leaves. Excellent air purifier and low-light tolerant.',
    image: '🌺',
  },
  {
    id: 5,
    name: 'Lavender',
    category: 'Outdoor',
    price: 14.99,
    description: 'Fragrant purple flowers that attract pollinators. Perfect for gardens and containers.',
    image: '🌸',
  },
  {
    id: 6,
    name: 'Rose Bush',
    category: 'Outdoor',
    price: 34.99,
    description: 'Classic garden beauty with stunning blooms in various colors. Fragrant and long-lasting.',
    image: '🌹',
  },
  {
    id: 7,
    name: 'Succulent Collection',
    category: 'Succulents',
    price: 22.99,
    description: 'Set of 5 easy-care succulents in assorted varieties. Perfect for desktops and sunny spots.',
    image: '🌵',
  },
  {
    id: 8,
    name: 'Aloe Vera',
    category: 'Succulents',
    price: 16.99,
    description: 'Healing plant with soothing gel inside leaves. Great for burns and skincare.',
    image: '🌵',
  },
  {
    id: 9,
    name: 'Boston Fern',
    category: 'Indoor',
    price: 18.99,
    description: 'Lush feathery fronds that cascade beautifully. Loves humidity and indirect light.',
    image: '🌿',
  },
  {
    id: 10,
    name: 'Sunflower',
    category: 'Outdoor',
    price: 9.99,
    description: 'Cheerful tall flowers that follow the sun. Easy to grow from seed, great for children.',
    image: '🌻',
  },
  {
    id: 11,
    name: 'Cactus Mix',
    category: 'Succulents',
    price: 12.99,
    description: 'Assorted small cacti in decorative pots. Minimal watering needed, maximum character.',
    image: '🌵',
  },
  {
    id: 12,
    name: 'Jade Plant',
    category: 'Succulents',
    price: 20.99,
    description: 'Symbol of good luck and prosperity. Thick glossy leaves with woody stems.',
    image: '🌱',
  },
]

export const categories = ['All', 'Indoor', 'Outdoor', 'Succulents']

export default productsData
